import type { Metadata } from "next";
import * as GovUK from './components/govuk';
import "./main.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={"govuk-template"}>
      <body className={"govuk-template__body"}>
      <GovUK.Header />
      <GovUK.PhaseBanner />
      {children}
      <GovUK.Footer />
      </body>
    </html>
  );
}
